pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Building the project... Skipping the TESTS!!!!'
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests...!!!!!'
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                echo 'Delivering the project...!!!!'
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
