pipeline {
    agent any
    stages {
        stage('Hello') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'jenkins', url: 'git@github.com:jpkucharski/simple-java-maven-app.git']])
            }
        }       
        stage('Check Environment') {
                steps {
                    sh 'printenv'
                }
        }
        stage('AWS cred') {
            steps{
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: "jenkins_to_aws_credentials",
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                ]]) {
                    sh "aws ec2 describe-instances --region eu-central-1"
                }
            }
        }
        stage('Build') {
            steps {
                echo 'Building the project... Skipping the TESTS!!!!'
                sh 'mvn clean'
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests...!!!!!'
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                echo 'Delivering the project...!!!!'
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
